version: "3.9"
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/migrations/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    #env_file:
    #- ./docker/db_creds.env
    environment:
      POSTGRES_DB: arrow
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:

