-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


loading : Translations -> String
loading translations =
    t translations "loading"


cancel : Translations -> String
cancel translations =
    t translations "cancel"
