-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Settings.Labels exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


language : Translations -> String
language translations =
    t translations "settings.labels.language"
