-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.BowSelection exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


emptyList : Translations -> String
emptyList translations =
    t translations "bowSelection.emptyList"


saveBow : Translations -> String
saveBow translations =
    t translations "bowSelection.saveBow"


newBow : Translations -> String
newBow translations =
    t translations "bowSelection.newBow"


name : Translations -> String
name translations =
    t translations "bowSelection.name"


maxDrawDistance : Translations -> String
maxDrawDistance translations =
    t translations "bowSelection.maxDrawDistance"


remainderArrowLength : Translations -> String
remainderArrowLength translations =
    t translations "bowSelection.remainderArrowLength"
