-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Error exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


required : Translations -> String
required translations =
    t translations "error.required"


tooSmall : Translations -> String
tooSmall translations =
    t translations "error.tooSmall"


tooBig : Translations -> String
tooBig translations =
    t translations "error.tooBig"


numberRequired : Translations -> String
numberRequired translations =
    t translations "error.numberRequired"
