-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Error exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


required : Translations -> String
required translations =
    t translations "error.required"


tooSmall : Translations -> String
tooSmall translations =
    t translations "error.tooSmall"


tooBig : Translations -> String
tooBig translations =
    t translations "error.tooBig"


numberRequired : Translations -> String
numberRequired translations =
    t translations "error.numberRequired"


unexpectedArgNum : Translations -> String -> String -> String
unexpectedArgNum translations expected actual =
    tr translations Curly "error.unexpectedArgNum" [ ( "expected", expected ), ( "actual", actual ) ]


unexpectedMessageType : Translations -> String -> String -> String
unexpectedMessageType translations expected actual =
    tr translations Curly "error.unexpectedMessageType" [ ( "expected", expected ), ( "actual", actual ) ]


unexpectedDeletion : Translations -> String -> String
unexpectedDeletion translations deletion =
    tr translations Curly "error.unexpectedDeletion" [ ( "deletion", deletion ) ]


timeout : Translations -> String
timeout translations =
    t translations "error.timeout"


badStatus : Translations -> String -> String
badStatus translations status =
    tr translations Curly "error.badStatus" [ ( "status", status ) ]


badBody : Translations -> String -> String
badBody translations error =
    tr translations Curly "error.badBody" [ ( "error", error ) ]


badUrl : Translations -> String -> String
badUrl translations url =
    tr translations Curly "error.badUrl" [ ( "url", url ) ]


networkError : Translations -> String
networkError translations =
    t translations "error.networkError"
