-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Header exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


shooting : Translations -> String
shooting translations =
    t translations "header.shooting"
