-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Home exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


newMeasurement : Translations -> String
newMeasurement translations =
    t translations "home.newMeasurement"


manageMeasurements : Translations -> String
manageMeasurements translations =
    t translations "home.manageMeasurements"


calibration : Translations -> String
calibration translations =
    t translations "home.calibration"


help : Translations -> String
help translations =
    t translations "home.help"
