-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Parameters exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


or : Translations -> String
or translations =
    t translations "parameters.or"


name : Translations -> String
name translations =
    t translations "parameters.name"


interval : Translations -> String
interval translations =
    t translations "parameters.interval"


restHeight : Translations -> String
restHeight translations =
    t translations "parameters.restHeight"


drawDistance : Translations -> String
drawDistance translations =
    t translations "parameters.drawDistance"


drawForce : Translations -> String
drawForce translations =
    t translations "parameters.drawForce"
