-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Warning exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


tooSmall : Translations -> String
tooSmall translations =
    t translations "warning.tooSmall"


tooBig : Translations -> String
tooBig translations =
    t translations "warning.tooBig"
